version: 2

sources:
  - name: raw_data
    tables:
      - name: orders
        meta:
          external_location: "read_parquet('s3://{{ env_var('BUCKET_NAME') }}/data/raw_data/orders/*.parquet', filename=true)"
        columns:
          - name: dt
            data_type: varchar
          - name: filename
            data_type: varchar
          - name: order_id
            data_type: varchar
          - name: quantity
            data_type: varchar
          - name: purchase_price
            data_type: varchar
          - name: sku
            data_type: varchar 
  # - name: landing
  #   tables:
  #     - name: landing_orders
  #       meta:
  #         dagster:
  #           asset_key: ["landing_orders"]
  #         external_location: "read_parquet('s3://{{ env_var('BUCKET_NAME') }}/data/landing/orders/*.parquet')"
  #       columns:
  #         - name: dt
  #           data_type: varchar
  #         - name: filename
  #           data_type: varchar
  #         - name: order_id
  #           data_type: varchar
  #         - name: quantity
  #           data_type: varchar
  #         - name: purchase_price
  #           data_type: varchar
  #         - name: sku
  #           data_type: varchar
  - name: staging
    tables:
      - name: staging_orders_per_month
        meta:
          dagster: 
            asset_key: ["staging_orders_per_month"]
          external_location: "s3://newsletter-multiengine-stack/data/staging/orders_per_month/orders_per_month.parquet"
        columns:
          - name: month
            data_type: bigint
          - name: year
            data_type: bigint
          - name: total_orders_per_month
            data_type: bigint
          - name: total_quantity_per_month
            data_type: float